name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.REGISTRY_ENDPOINT }}/python3:${{ github.sha }}
    - uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_ENDPOINT }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: docker push ${{ secrets.REGISTRY_ENDPOINT }}/python3:${{ github.sha }}
    - uses: azure/container-scan@v0
      with:
        image-name: ${{ secrets.REGISTRY_ENDPOINT }}/python3:${{ github.sha }}
